### ISSUE TITLE
Error when calling snakemake pipeline

### ISSUE THREAD

**Issue by AndresCongenica** [Ax-Sch/AlphScore#3]
I followed all instructions, including those provided by SimTK for the FEATURE framework.
Yet, when calling the pipeline, I get the following error before it stops. I could change the code to avoid the issue but I was wondering if you had another suggestion.

`snakemake --cores 1 --use-conda --conda-frontend conda
/home/AlphScore/workflow/Snakefile:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Traceback (most recent call last):
  File "/opt/conda/envs/AlphScore/lib/python3.10/site-packages/snakemake/__init__.py", line 701, in snakemake
    success = workflow.execute(
  File "/opt/conda/envs/AlphScore/lib/python3.10/site-packages/snakemake/workflow.py", line 1060, in execute
    logger.run_info("\n".join(dag.stats()))
  File "/opt/conda/envs/AlphScore/lib/python3.10/site-packages/snakemake/dag.py", line 2191, in stats
    yield tabulate(rows, headers="keys")
  File "/opt/conda/envs/AlphScore/lib/python3.10/site-packages/tabulate/__init__.py", line 2048, in tabulate
    list_of_lists, headers = _normalize_tabular_data(
  File "/opt/conda/envs/AlphScore/lib/python3.10/site-packages/tabulate/__init__.py", line 1471, in _normalize_tabular_data
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/opt/conda/envs/AlphScore/lib/python3.10/site-packages/tabulate/__init__.py", line 1471, in <lambda>
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/opt/conda/envs/AlphScore/lib/python3.10/site-packages/tabulate/__init__.py", line 107, in _is_separating_line
    (len(row) >= 1 and row[0] == SEPARATING_LINE)
  File "/opt/conda/envs/AlphScore/lib/python3.10/site-packages/snakemake/rules.py", line 1138, in __eq__
    return self.name == other.name and self.output == other.output
AttributeError: 'str' object has no attribute 'name'`

**Comment by Ax-Sch** [comment]
Dear Andres, thank you for the raising the issue. I will look into this tomorrow. Best, Axel

**Comment by AndresCongenica** [comment]
Hi Axel,
It seems that the issue was with library versioning as it has been mostly resolved when working on the "AlphScore_exact_versions_for_documentation.yaml" environment. However, a separate issue seems to have appeared in that one of the links for alphafold files doesn't seem to work. Kindly see below.

Resolving dbnsfp.softgenetics.com (dbnsfp.softgenetics.com)... 70.90.238.194
Connecting to dbnsfp.softgenetics.com (dbnsfp.softgenetics.com)|70.90.238.194|:21... --2022-12-16 10:35:53--  https://ftp.ebi.ac.uk/pub/databases/alphafold/latest/UP000005640_9606_HUMAN_v2.tar
Resolving ftp.ebi.ac.uk (ftp.ebi.ac.uk)... connected.
193.62.193.138
Connecting to ftp.ebi.ac.uk (ftp.ebi.ac.uk)|193.62.193.138|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-12-16 10:35:53 ERROR 404: Not Found.

**Comment by Ax-Sch** [comment]
Hi, 
okay, good to know!
Regarding the link: I corrected the config.yaml - the file was moved to a different directory (https://ftp.ebi.ac.uk/pub/databases/alphafold/v2/UP000005640_9606_HUMAN_v2.tar).
Best regards,
Axel

**Comment by Ax-Sch** [comment]
The error above was probably related to the following snakemake issue: 
https://github.com/snakemake/snakemake/issues/1899
I now changed the AlphScore.yaml environment to prevent the issue
